config/routes.rb
Rails.application.routes.draw do

  root 'widgets#index'
  resources :widgets

end

app/models/setting.rb
class Setting < ActiveRecord::Base
end

app/models/widget.rb
class Widget < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController
	def index
		@widgets = Widget.all
	end

	def show

	end

	def new
		render layout: "widget_creator"
		@widget = Widget.new
	end

	def create

	end

	def update

	end

	def destroy

	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def icon_button(icon = nil, tooltip: nil, text: nil)
		string = ""
		string += "<button title='#{tooltip}'>" if tooltip
		string += "<i class='fa fa-#{icon}'></i>"
		string += text if text
		string += "</button>" if tooltip
		return string.html_safe
	end
end

app/helpers/widgets_helper.rb
module WidgetsHelper
	def get_widget_style
		return 'color: #222; background: #000;'
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Widgets</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/widget_creator.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Widget Creator</title>
  <%= stylesheet_link_tag "widget_creator" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="app-container">
		<div id="header-bar">
			<span class="header-bar-title">Widget Creator</span>
		</div>
		<%= yield %>
	</div>
</body>
</html>

app/views/widgets/_widget.html.erb
<div class="widget-container" style="<%= get_widget_style %>">
	<div class="widget-title">title</div>
</div>

app/views/widgets/index.html.erb
<h1>All Widgets</h1>

<table>
	<tr>
		<th>Name</th>
		<th>Actions</th>
	</tr>
	<tr>
		<% @widgets.each do |widget| %>
			<td><%= widget.name %></td>
			<td><%= link_to "Show Widget", widget_show_path %>
			<%= link_to "Create Widget" %>
			<%= link_to "Delete Widget" %></td>
		<% end %>
	</tr>
</table>

<%= link_to 'Create new Widget', new_widget_path, class: 'pure-button' %>

app/views/widgets/new.html.erb
<script>
	a = document.getElementById('workspace');
	a.
</script>
<div id="app">
	<div class="window-toolbar">
		<ul>
			<li><span class="description">Data</span></li>
			<li><%= icon_button "save", tooltip: "Save this widget." %></li>
			<li><%= icon_button "undo", tooltip: "Undo last step." %></li>
		</ul>
		<ul>
			<li><span class="description">Font</span></li>
			<li><%= icon_button "bold", tooltip: "Bold font." %></li>
			<li><%= icon_button "italic", tooltip: "Italic font." %></li>
			<li><%= icon_button "underline", tooltip: "Underline text." %></li>
		</ul>
	</div>

	<div id="workspace">
		<div id="sidebar-components" class="sidebar">
			<div class="sidebar-title">
			<%= icon_button 'angle-double-right' %>
			<span class="title">Components</span>
			</div>
			<div class="sidebar-content">
			awd
			</div>
		</div>
		<div id="widget-editor">
			<%= render(partial: 'widget', widget: @widget) %>
		</div>
	</div>
</div>